cozy/cozy-keys-lib

src/WebVaultClient.js
Allows to search a cipher by its id.
If the id is null or the cipher doesn't exist, then search an
existing cipher by other criterias, and get the first one
found based on a specific order
=> feat: getByIdOrSearch

src/WebVaultClient.js
This function was a mistake from me.
Please use `decrypt()` for the same (correct) behaviour
=> refactor: Removes getData

src/components/UnlockForm.jsx
In `UnlockForm`, the import path to cozy-ui's Modal component was not good.
=> fix(UnlockForm): Cozy ui react Modal import path

src/WebVaultClient.js
We had to put a `vaultClient.sync()` after login in cozy-harvest-lib. Removing it caused the following error:
```js
TypeError: "eqDomains is null"
eqDomainsPromise cipher.service.js:678
```
This means that we were not doing the `sync` at the good time.
I tried
```js
await this.login(masterPassword)
await this.sync()
```
But it didn't work. The only thing that succeeds was to do `await this.sync()` before emitting the `login` event.
=> fix(WebVaultClient): Sync before emitting login event

src/components/UnlockForm.jsx, src/components/VaultUnlocker.jsx
The lock screen has buttons to quit, but at the moment they can't be connected to anything. With this PR we can pass a prop to control what happens. 
Still trying to make unit tests work, but this can already be reviewed.
=> Ability to dismiss the lock screen

src/components/UnlockForm.jsx
Having the form outside the modal prevented it from registering that the enter key press was a form submission.
With the form inside the modal, we need some utility classes to prevent the layout from breaking on mobile.
=> fix: Unlock form with enter

src/WebVaultClient.js, src/WebVaultClient.spec.js
The bitwarden lib uses a global variable that contains the decryption key.
We had a bug where, if multiple vault client instances were created, the first one would set the global variable, and all other ones would start using that global variable. If the first client wasn't logged in, all other clients would fail to decrypt data because there was no key to use.
There are legitimate use cases for creating multiple client instances over the lifetime of a page.
The fix proposed here is to make sure the global variable is always bound to the correct instance before attempting any crypto operations.
=> Storage singleton

src/WebVaultClient.js
Do not try to write a share if the cipher is already shared
=> refactor: share with cozy only when not already in cozy org

babel.config.js, package.json, src/stubs/node-forge.js, src/stubs/null.js, yarn.lock
Our bundle was pretty large. By mapping some unused modules to `null` or reduced versions, we can optimize it a little.
| | Original | Step 1 : -zxcvbn | Step 2 : -tldjs | Step 3 : -sweetalert | Step 4 : -unused node-forge parts |Reduction|
|-|----------|---------|--------|-------------|--------------------------|---|
|Stats size|2.93 MB|2.12 MB|1.96 MB|1.92 MB|1.66MB|-43%|
|Parsed size|1.68 MB|920.68 KB|773.59 KB|734.13 KB|648.52 KB|-61%|
|Gzipped size|619.08 KB|232.04 KB|197.59 KB|187.03 KB|163.36 KB|-73%|
=> Bundle size optimizations

babel.config.js
When using absolute paths, the paths generated on travis are used in the
module published on npm, so everything breaks. We get errors like `Error: Can't resolve '/home/travis/build/cozy/cozy-keys-lib/src/stubs/node-forge.js'`. Using relative paths fixes this.
=> fix: Use relative path for import redirects

src/components/UnlockForm.jsx
By default, the button is of type submit. But it should not trigger the
form submit when clicking on it or typing on the enter key. Settings its
type to button fixes the problem.
=> fix(UnlockForm): The cancel button should be of type button

src/components/UnlockForm.jsx, src/components/VaultUnlocker.jsx
In some context, like intents modals, there is already a close cross to
close the modal, so we don't want to render the unlock form cross. To
achieve that we use the Modal's closable prop.
=> feat: Make unlock form closable

src/components/UnlockForm.jsx, src/components/VaultUnlocker.jsx
We consider a user doesn't use the password manager feature as long as he
doesn't have any cipher. In that case, we don't want him to unlock his
empty unused vault. So we consider that an empty vault as always unlocked.
When the user uses the Cozy web browser extension for the first time, his
existing accounts will be added to its vault, then we will consider that he
is using the vault.
=> Consider an empty vault as unlocked

src/components/VaultUnlocker.jsx, src/utils.js
Previously we auto unlocked the vault by checking if we can find some ciphers shared with the cozy org directly in couch databases.
This doesn't work in all cases as it's possible that:
* The vault contains ciphers not shared with the cozy org
* The vault has been initialized, but is empty
So now we also check for the cozy org existence. The condition to ask for the user to unlock his vault is now the existence of some ciphers or the existence of the cozy org.
=> Update auto unlock condition

src/components/VaultUnlocker.jsx, src/utils.js
It turns out that the cozy org is created when the instance is created.
It means it's always there, so checking its existence is useless. We
decided to only check the presence of ciphers for now.
=> feat(VaultUnlocker): Update should unlock condition

jest.config.js, jest.setup.js, package.json, src/components/VaultUnlocker.jsx, src/utils.js, src/utils.spec.js, yarn.lock
We figured than only checking if some ciphers exist is not a strong
enough condition to know if we should ask the user to unlock the vault
or not.
To resolve our problems, the stack now adds a
`extension_installed` attribute on the `io.cozy.settings.bitwarden`
document when an extension has been connected for the first time to the
instance. See https://github.com/cozy/cozy-stack/pull/2315.
So we now check this attribute. The flow is now:
* Check if there is some cipher, is yes => the user should unlock
* If there is no cipher, check if the extension has been installed, if
yes => the user should unlock
* Otherwise, skip the unlock step
=> feat: Check if extension has been installed before ask for unlock

src/components/PasswordField.jsx
This caused a prop types warning as the label prop is required on
cozy-ui's button
=> fix(PasswordField): Add label on input adornment

package.json, yarn.lock
Locking the cozy-ui version will most likely result in multiple cozy-uis embedded in an app build. We should not lock the version in a library.
Also update cozy-ui.
=> Don't lock cozy-ui version and update it

babel.config.js
Stubbing tldjs didn't throw an error while I was working on #43,
replacing tldjs by a stub file didn't break tests nor harvest. Actually,
it's required but bitwarden's jslib has defensive code to handle its
absence (see
https://github.com/bitwarden/jslib/blob/master/src/misc/utils.ts#L198).
The problem is that the behavior is not the same with and without it.
And it prevented us from matching `www.tartanpion.com` with
`tartanpion.com` in harvest. Thus not proposing a cipher to the user
because the konnector's vendor_link is `tartanpion.com`, but the cipher
has been created with `www.tartanpion.com` URI.
=> fix: Don't stub tldjs dep

package.json, src/index.node.js
This is useful when making CLI for libraries using cozy-keys-lib
like harvest
=> feat: Add node version without React components

package.json, src/WebVaultClient.js, src/WebVaultClient.spec.js, yarn.lock
We can't use the ImportService's `import` method because it does a call
to a `/ciphers/import`, which is not yet implemented by the stack. So I
reimplemented a basic import feature that only handles the ciphers. It
only uses the jslib's import formats and parsers so we cover all
possible formats.
For each imported cipher, it looks for an existing one by
{username,password,uri} tuple. If it finds an existing cipher, it adds
the URIs that are in the imported cipher but not in the existing one to
it. If it doesn't find an existing cipher, it creates a new one with the
imported cipher data.
The potential problem with this is that we will have 1 request per cipher to create/update. With the `/ciphers/import` route, we would have only 1 request.
=> feat: Add import

package.json, src/WebVaultClient.js, yarn.lock
Importing ciphers in parallel makes it 10x faster on a batch of 100
ciphers.
Previously ciphers were imported sequentially, which was not so effective because lot of steps in the import process are asynchronous, so we didn't take advantage of this.
Related to https://github.com/cozy/cozy-keys-lib/pull/81#discussion_r385008465
=> perf(import): Import ciphers in parallel

package.json
Using a normal dep for react would introduce in apps two versions of
React where we only want 1. The symptom in apps would be error when
using hooks since we were importing the hook function from 1 version
of React and using it in another React instance
=> fix: Move deps to peerDeps

src/WebVaultClient.js
Before, the matching of a cipher was done just before saving.
For batch import, we need to be able to have a matching phase for all
ciphers and then a saving phase where we send all ciphers. Here we
refactor the code to make the matching phase more apparent (mapping all
ciphers into prepareCipherToImport) and then we save them all. In a
future commit, the map to saveCipher will be replaced by a batch save.
=> refactor: Separate cipher matching from cipher saving

package.json, src/WebVaultClient.js, src/WebVaultClient.spec.js, src/tests/exports/keepass.csv, yarn.lock
The /ciphers/import route is being added on the stack. This PR makes use of it.
⚠️ This is very crude, it makes use directly of the apiService instead of going through [import service](https://github.com/bitwarden/jslib/blob/ab9bee29b8ebf0b2812fcc5e5a8e7c36a3868ebd/src/services/import.service.ts#L287). This means that folder relationships are not retained, but at least we can match ciphers whereas the bitwarden code does not try to merge the imported ciphers. I am not sure that we want to retain folder relationships at this point.
=> feat: Use import API

src/WebVaultClient.js, src/WebVaultClient.spec.js
If we do not wrap into CipherRequest, encrypted values
are not unwrapped.
=> fix: Wrap cipher contents into CipherRequest

src/components/VaultUnlocker.jsx
When using `VaultUnlocker` with no children, an error `Error: VaultUnlocker(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.` is raised
=> fix: Render null if no children

src/CozyUtils.js, src/components/UnlockForm.jsx, src/components/VaultContext.jsx, src/components/VaultUnlocker.jsx
- Use a single web vault client per page load
- Show unlocker spinner inside an overlay (otherwise it was floating
in the middle of nowhere)
=> Improvements

src/components/VaultUnlockPlaceholder.jsx, src/components/VaultUnlocker.jsx, src/components/defaults.js, src/components/vaultUnlockContext.jsx, src/components/vaultUnlockContext.spec.jsx, src/index.js
Moved code that was originally in Harvest so that all code managing the 
vault is in cozy-keys-lib Additionally, an additional check in
showUnlockForm has been added to check if the extension has been installed.
This way, the user of the lib, does not need to do the check. If the
extension is not installed or if the vault already is unlocked, onUnlock is
called immediately.
=> feat: Move VaultUnlock components from harvest

src/stubs/null.js
stubs/null is used to remove large unused files from what's built
inside cozy-keys-lib. Unfortunately, since it did not export
EEFLongWordList, we would have warnings inside webpack telling us
that EEFLongWordList was not exported from stubs/null. Since we do
not use currently this long word list, and we do not want to have this
warning polluting our consoles, let's export an empty list here.
No more warnings for the users of the lib !
=> fix: Remove warnings for users of the lib

package.json, src/components/UnlockForm.jsx, src/locales/en.json, src/locales/fr.json, yarn.lock
For cozies that authenticate with an external provider, we want to
make sure that the unlock vault modal is precise enough so that
the user enters the vault password and not its Cozy password.
We change the icon and the text to show that the password that is to be entered is the vault one.
=> feat: Specific vault unlocker display for oidc

src/WebVaultClient.js, src/WebVaultClient.spec.js, src/components/VaultContext.jsx
When used from `cozy-pass-web`, `WebVaultClient` may override local `jslib` when it is instantiated.
To avoid this dependency injection may be used.
Dependency injection is optional to keep compatibility with other libs.
It will allow to not trigger `jslib` imports and so local `jslib` is preserved.
=> feat: add optional dependency injection to VaultContext

src/WebVaultClient.js, src/WebVaultClient.spec.js
Previous version introduced unnecessary complexity as `kdfIterations` and `kdf` were ignored by `authService.makePreloginKey()`
Also the `iterations` handling did not work correctly as the ternary operator was reversed
As the only value of `authService.makePreloginKey()` is to query `kdfIterations` and `kdf` and because we never call `computeMasterKey()` with those values unset, then we call `cryptoService.makeKey()` directly
=> fix: call `cryptoService.makeKey` directly form `computeMasterKey`

src/WebVaultClient.js, src/WebVaultClient.spec.js
This adds methods in order to encrypt/decrypt binary files
A notable difference with bitwarden's ciphers is that we need to generate new
encryption keys: all the ciphers are encrypted with the the same vault
encryption key, while we want a specific encryption key for each
encrypted directory.
=> feat: Add file encryption methods

src/components/VaultContext.jsx, src/components/VaultContext.spec.jsx, src/components/VaultUnlocker.jsx, src/index.js
It can be useful to pass an initialized client to VaultContext
in case it must be shared between react components and redux store.
This avoids ending up with several client instance, holding different
states.
=> feat: Allow passing client as props in VaultContext

src/components/VaultContext.jsx, src/components/VaultUnlocker.jsx, src/components/defaults.js, src/components/defaults.spec.js, src/components/vaultUnlockContext.jsx, src/components/vaultUnlockContext.spec.jsx
We used to check if a bitwarden client was installed when checking if the vault has to be unlocked. This is notably useful to harvest, that should not display the vault form if no pass client is used.
But this check is not always relevant, typically, it is not useful for the incoming Drive folder encryption. Therefore, we only check if the vault is locked by default, and let the possibility to define a function in props to add any check the app might want to do.
Note this includes a breaking change, described in 5df51a9
=> feat: Do not force the extension installation check on unlock

src/components/VaultContext.jsx, src/components/VaultContext.spec.jsx
We can now pass a cozy-client instance in VaultProvider props, so we can
listen for login event and retrieve the uri to init the vault.
This will be useful in mobile context, because the uri is not already
available the onboarding is not done.
=> feat: Init vaultClient with cozy-client uri

src/index.js
Since cc8f07932ca400afce1d82f3d73c27f6bfe28074, the UnlockForm is
exported. However, this was wrongly exported as it is default exported
in the component. Thus, this cannot work and triggers a warning in apps
using the lib such as Drive: `export 'UnlockForm' was not found`.
Consequently, we remove this useless export
=> fix: Remove broken UnlockForm export

package.json, src/logger.js, yarn.lock
The old alias to cozy git repo breaks build in other apps (eg bank)
I will then need to cherrypick on 3.8.1 and publish 3.8.1 for bank to use
=> fix: Use @cozy/minilog

.github/auto-merge.yml, .github/dependabot.yml
This will prevent dependabot update during weekdays
This will allow PR to be automerge when label merge added
=> chore(github): Add dependabot config and automerge

src/components/VaultContext.jsx
A cozy-client instance can be passed to the vault, so it can
be setup based on the client URL once it is logged. However,
the setup was never done when the login was already done and the
URL already provided.
=> fix: Setup client when init with cozy-client instance

package.json, src/components/UnlockForm.jsx, yarn.lock
Currently, opening the UnlockForm on HomePage in Amirale App will trigger the icons to black. Instead, we want them to be white. This lib has to be updated.
Fixes [# (issue)](https://trello.com/c/nFvqeznK/402-corriger-les-status-bar-nav-bar-sur-lensemble-des-%C3%A9crans)
Please delete options that are not relevant.
This has been tested manually only, in local dev env. Physical and emulated Android device.
=> fix: Handle Amirale App UI update
